#apiVersion: v1
#kind: Secret
#metadata:
#  name: git-auth
#  namespace: tekton-pipelines
#  annotations:
#    build.knative.dev/git-0: http://git.xxxx.com
#type: kubernetes.io/basic-auth
#stringData:
#  username: xxxx 
#  password: xxxx

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: docker-auth
#  namespace: tekton-pipelines
#  annotations:   
#    build.knative.dev/docker-0: https://layershop.xxxx.com
#type: kubernetes.io/basic-auth
#stringData:
#  username: xxxx
#  password: xxxx

#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: docker-git-auth-sa
#  namespace: tekton-pipelines
#secrets:
#  - name: git-auth
#  - name: docker-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-git-secret
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: http://git.xxxx.com
    tekton.dev/docker-0: https://layershop.xxxx.com
type: kubernetes.io/basic-auth
stringData:
  username: xxxx 
  password: xxxx

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-git-sa
  namespace: tekton-pipelines
secrets:
  - name: docker-git-secret

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tutorial-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"  
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tutorial-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tutorial-role
subjects:
- kind: ServiceAccount
  name: docker-git-sa
  namespace: tekton-pipelines
