apiVersion: v1
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1...
        server: https://cluster1.k8s.arch.api:6443
      name: cnlab
    contexts:
    - context:
        cluster: cnlab
        user: kubernetes-admin
      name: kubernetes-admin@cnlab
    current-context: kubernetes-admin@cnlab
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSU...
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2...
kind: ConfigMap
metadata:
  name: k8s-config
  namespace: tekton-pipelines
