apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: taskrun-productapi
  namespace: tekton-pipelines
spec:
  inputs:
    params:
    - name: dockerfilename
      value: /workspace/git-workspace/dockerfiletest
    resources:
#    - name: git-workspace
#      resourceRef:
#        name: pipeline-resource-java-gitsource
    - name: git-workspace
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/xxx/knative-helloworld-php.git
        - name: revision
          value: master
  outputs:
    resources:
#    - name: builtImage
#      resourceRef:
#        name: pipeline-resource-java-builtimage
    - name: builtImage
      resourceSpec:
        type: image
        params:
        - name: url
          value: xxx/cnlab/api:v1
  serviceAccount: docker-git-auth-sa
  taskRef:
    name: task-php-template
